// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using iOStore.Data;

#nullable disable

namespace iOStore.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260403110000_m16_DashboardFix")]
    partial class m16_DashboardFix
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
