// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using iOStore.Data;

#nullable disable

namespace iOStore.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260403100000_m15_TarifasYSPFix")]
    partial class m15_TarifasYSPFix
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
