// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using iOStore.Data;

#nullable disable

namespace iOStore.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260403010002_m13_PedidoEdicion")]
    partial class m13_PedidoEdicion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
