// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using iOStore.Data;

#nullable disable

namespace iOStore.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260403120000_m17_EstadisticasPagoFix")]
    partial class m17_EstadisticasPagoFix
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
