// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using iOStore.Data;

#nullable disable

namespace iOStore.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260411120000_m19_AddPromocionMetodoPagoId")]
    partial class m19_AddPromocionMetodoPagoId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
