// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using iOStore.Data;

#nullable disable

namespace iOStore.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260403130000_m18_FixCaraChicaRecargo")]
    partial class m18_FixCaraChicaRecargo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
