// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using iOStore.Data;

#nullable disable

namespace iOStore.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260415000000_m23_EntregadoFiltroYSPFix")]
    partial class m23_EntregadoFiltroYSPFix
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
