// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using iOStore.Data;

#nullable disable

namespace iOStore.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260403010001_m12_Notificaciones")]
    partial class m12_Notificaciones
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
