// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using iOStore.Data;

#nullable disable

namespace iOStore.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260403010000_m11_ChartSPs")]
    partial class m11_ChartSPs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
